/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.net.ServerSocket;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.User;

/**
 *
 * @author Tien Thanh
 */
public class HomeView extends javax.swing.JFrame {

    /**
     * Creates new form HomeView
     */
    ServerSocket server = null;
    Socket s=null;
    User user=null;
    String[] temp;
    DataOutputStream outputStream = null;
    DataInputStream inputStream = null;
    Boolean isConnect=false;
    String request;
    String response;

    public HomeView(User user) throws IOException {
        initComponents();
        this.user=user;
        lbText.setText("Xin chào: " + user.getName());
        outputStream = new DataOutputStream(user.getSocket().getOutputStream());
        inputStream = new DataInputStream(user.getSocket().getInputStream());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGhep = new javax.swing.JButton();
        btnVaoPhong = new javax.swing.JButton();
        lbText = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnGhep.setText("Ghép");
        btnGhep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGhepActionPerformed(evt);
            }
        });

        btnVaoPhong.setText("Vào phòng");
        btnVaoPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVaoPhongActionPerformed(evt);
            }
        });

        lbText.setText("Xin chào");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnVaoPhong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnGhep, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(lbText)))
                .addContainerGap(161, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lbText)
                .addGap(56, 56, 56)
                .addComponent(btnGhep)
                .addGap(26, 26, 26)
                .addComponent(btnVaoPhong)
                .addContainerGap(120, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVaoPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVaoPhongActionPerformed
        try {
            // TODO add your handling code here:
            // nhan DS phong
            request="vaophong-"+user.getName();
            outputStream.writeUTF(request);
System.out.println("Yeu cau: "+request);
            String list=inputStream.readUTF();
System.out.println(list);
            Table table=new Table(user,list);
            table.setLocationRelativeTo(this);
            table.setVisible(true);
            
            
        } catch (IOException ex) {
            Logger.getLogger(HomeView.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnVaoPhongActionPerformed

    private void btnGhepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGhepActionPerformed
        // TODO add your handling code here:
        request = "ghep-" + user.getName();
        try {
            outputStream.writeUTF(request);
System.out.println("Yeu cau: "+request);
        } catch (IOException ex) {
            Logger.getLogger(HomeView.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            response = inputStream.readUTF();
System.out.println("phan hoi: "+request);
            if (response.equals("CreateServer")) {
                try {
                    server = new ServerSocket(1108);
                    JOptionPane.showMessageDialog(this,"Vui lòng chờ người chơi khác!");
                } catch (IOException ex) {
                    System.out.println(ex.getMessage());
                }

                while (true) {
                    try {
                        
                        s = server.accept();
                       
                        if (s != null) {
                            user.setSocket(s);
                            inputStream= new DataInputStream(s.getInputStream());
                            String name=inputStream.readUTF();
                            JOptionPane.showMessageDialog(rootPane,"Ghép thành công");
                            Form ui = new Form(user,name);
                            
                            ui.setVisible(true);
                            Thread t1 = new Thread(ui);
                            t1.start();
                            isConnect = true;
                        }

                    } catch (Exception ex) {
                        System.out.println(ex.getMessage());
                    }
                    if (isConnect == true) {
                        break;
                    }

                }
                this.dispose();
                isConnect=false;
            } else {
                temp = response.split("-");
                String ip = temp[1];
                System.out.println(ip);
                String name = temp[2];
                System.out.println("client: " + name);
                try {
                    s = new Socket(ip, 1108);
                    user.setSocket(s);
                    String myName=user.getName();
                    outputStream=new DataOutputStream(s.getOutputStream());
                    outputStream.writeUTF(myName);
                    JOptionPane.showMessageDialog(this, "Ghép thành công");
                    Form ui = new Form(user,name);
                    ui.setVisible(true);
                    Thread t = new Thread(ui);
                    t.start();

                } catch (IOException ex) {
                    System.out.println(ex.getMessage());
                }
            }
        } catch (IOException ex) {
            Logger.getLogger(HomeView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnGhepActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGhep;
    private javax.swing.JButton btnVaoPhong;
    private javax.swing.JLabel lbText;
    // End of variables declaration//GEN-END:variables
}
